services:
  app:
    build: .
    container_name: job-posting-service
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: job-posting-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_posting
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
