version: '3.8'

services:
  app:
    build: .
    container_name: job-posting-service
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend

  db:
    image: postgres:15
    container_name: job-posting-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_posting
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: supersecure
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend

volumes:
  pgdata:
  rabbitmq_data:

networks:
  backend:
